### ISSUE TITLE
Making the wrapper even better

### ISSUE THREAD

**Issue by felix91gr** [Ponyboy47/Cinotify#2]
There is an issue when accessing the struct `inotify_event`: [the `name` member is missing when accessing it from Swift](https://stackoverflow.com/questions/43816692/c-struct-instance-is-missing-members-after-copying-it-to-swift). The SO community provided a fix, which translates into this in Swift:

```swift
fileSystemEvent = FileSystemEvent(
   watchDescriptor: WatchDescriptor(event.wd),
   name: String(cString: buffer + currentIndex + MemoryLayout<inotify_event>.size),
   mask: event.mask,
   cookie: event.cookie,
   length: event.len)
```

As they explained, the optional members of a _C struct_ aren't copied to the _Swift struct_. We can make this work on the wrapper, clearly. Wanna do it?

I'm fairly new to C-Swift interop, so please tell me where should I put the Swift source file (and what else should I move around) to make this work from the `inotify` wrapper.

Thanks in advance ^^,
Félix

**Comment by Ponyboy47** [comment]
I'm actually not sure how we could include this into the wrapper. I'm looking into this to see how we could extend/fix the imported structure from C. I'll let you know what I find. School started this week so I just got a lot busier unfortunately :/

**Comment by felix91gr** [comment]
Don't worry! I prefer to chill and take things at my pace... and same for others. Sorry if I made the wrong impression. I'm in no rush :) and please let me know if I can help you with this.

Also...
>  School started this week so I just got a lot busier unfortunately :/

Me too :disappointed:

:thinking: are you from the Southern Hemisphere? I don't know of any place in the Northern that starts school in August... I think. I'm from Chile :)

**Comment by Ponyboy47** [comment]
Glad you're not rushing me ;P

I'm actually from the USA. Texas is home, but I'm going to school in Utah right now!

**Comment by Ponyboy47** [comment]
So I actually went a little overboard here. I couldn't see a way to add swift wrappings to the c struct in the wrapper (although I didn't look very hard either), and so I ended up just writing a new inotify library and renamed this one to Cinotify to follow the common naming conventions I've seen with other swift libraries (ClibraryName = swift interop for importing C library and libraryName = swifty wrapper for ClibraryName). You can check it out at https://github.com/Ponyboy47/inotify. It's still in its infancy. Has the basic functionality, a few tests, pretty good error handling based on the errno used by inotify.

Sorry if this steps on what you were using this for...I'l try to actually spend some time finding a way to modify the swift wrapping around notify_event

**Comment by felix91gr** [comment]
Whaaaaaaat?! My god, it looks awesome!

Wow, nice. You managed to do so many things ✨

I’ll check this in more detail later, hopefully this week. Right now I’m
collapsed with uni work. Do you have a to-do list? I wanna help!

Thanks for continuing with this project. Thank you so much 💐

**Comment by Ponyboy47** [comment]
No problem! I love programming :)

Thanks for all the praise! I was worried it wasn't very good.

I haven't written a to-do yet, but a few things I know I want to improve:
- Better error handling while looping to watch events
- Find a way to actually stop select while it's waiting for events. (Currently it won't actually stop until after the next event gets triggered)
- Create a blockable event wait. One that doesn't run asynchronously so that it can actually throw errors

I'm sure I'll think of more as I work on it. I'll try to add a Todo section to the bottom of the readme sometime today. Any help you give will be more than welcome! If you hadn't brought up the shortcomings of this wrapper I never would have been motivated to make a better one :)

**Comment by felix91gr** [comment]
Now that I read it more carefully and remembered the library that I used the first wrapper for, I think that this new wrapper is actually aiming to be a full-fledged FS Events Watcher. Which is awesome :D

I want to help with its development, but for the time being I shouldn't promise anything because I'm actually doing just _too many things_. That said, I think `inotify` is important, and this project is probably the way forward to having it available in Swift.

During summer break (December-February) I should have the time necessary to help you kick off v1.0 or 1.5 :)
And after this is out of beta, I'll use it in my linux port of [SKDaemon](https://github.com/terhechte/SourceKittenDaemon). There, I'm using the [Watcher I showed](https://github.com/felix91gr/FileSystemWatcher) in the SO question, which in turn uses your original wrapper.

The SKD port is btw not done yet. It will be awesome when we ship it, but I can't yet resume development bc of uni. 
The good thing though, of not having time right now is that the dependencies will all be updated to Swift 4 when I go back to it :smile:

**Comment by Ponyboy47** [comment]
Yeah I really did want this to be full-featured. A last-stop for filesystemevent monitoring in swift on linux since I know it really is a pain without the built-in support that iOS and macOS have.

I finally got the Readme updated with some ToDo items :)

That SKDaemon looks awesome and super useful! What do you use for swift development on linux? I mostly just use vim for everything since that's what I use at work and am pretty good with it. I guess it's also because I do my linux swift development on a headless server I have and so I couldn't use a graphical editor anyways haha

**Comment by felix91gr** [comment]
> A last-stop for filesystemevent monitoring in swift on linux since I know it really is a pain without the built-in support that iOS and macOS have.

OMG, it is! This is exactly how I ended up in your project :)

> I finally got the Readme updated with some ToDo items :)

Wohooo :tada: 

> What do you use for swift development on linux?

Sublime, which apart from syntax coloring... it has no integration whatsoever.
So it's basically plain text + compiler to check if I'm doing things wrong :laughing:

**Comment by Ponyboy47** [comment]
Closing since it's been a few years
